home/urls.py
from django.urls import path

from . import views

# Importa la configuración global de tu proyecto Django
from django.conf import settings

# Importa la función 'static' para servir archivos estáticos como imágenes y hojas de estilo CSS, para que puedas ver cómo se ven en tu aplicación.
from django.conf.urls.static import static

app_name='Home'
# Define las URL de tu aplicación
urlpatterns = [
    path('', views.home, name='home'),
    
]

myPortafolioDj/urls.py
# Importa el módulo de administración de Django
from django.contrib import admin

# Importa funciones y clases relacionadas con las URL de Django
from django.urls import path, include

# Importa la configuración global del proyecto Django desde settings.py
from django.conf import settings

# Importa la función 'static' para manejar archivos estáticos y multimedia
from django.conf.urls.static import static

# Lista de patrones de URL del proyecto
urlpatterns = [
    # Ruta para acceder al panel de administración de Django
    path('admin/', admin.site.urls),
    
    # Incluye las URL de la aplicación 'home' usando el archivo urls.py de esa aplicación
    path('', include('home.urls')),

    # Incluye las URL de la aplicación 'Projects' usando el archivo urls.py de esa aplicación
    path('proyectos', include('projectos.urls')),
]

# Configuración para servir archivos estáticos y multimedia durante el desarrollo
if settings.DEBUG:
    # Agrega las URL para servir archivos multimedia (MEDIA_URL) usando la ruta del sistema de archivos especificada en MEDIA_ROOT
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectos/urls.py
from django.urls import path

from . import views


app_name='Projects'
# Define las URL de tu aplicación

urlpatterns = [
    path('', views.proyectos, name='proyectos'),
    
] 

home/models.py
from django.db import models

# Create your models here.

projectos/models.py
from django.db import models

# Create your models here.
class InfoProyectos2(models.Model):
    imagen = models.ImageField(upload_to='proyectos', null=True, blank=True)

    titulo = models.CharField(max_length=100)

    github_link = models.URLField(max_length=200, null=True, blank=True)

    link_proyecto = models.URLField(max_length=200, null=True, blank=True)

    introduccion = models.TextField()

    herramientas = models.TextField()

    resultadosLogros = models.TextField()

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'infoProyectos2'

        verbose_name="infoProyecto2"
    
    def __str__(self):
        return self.titulo

home/views.py
from django.shortcuts import render


# Create your views here.
def home(request):

    

    return render(request, 'home/index.html')

projectos/views.py
from django.shortcuts import render

from .models import InfoProyectos2

# Create your views here.
def proyectos(request):
    # Obtenemos todos los objetos de la clase 'InfoProyectos' de la base de datos y los almacenamos en informacion
    informacion = InfoProyectos2.objects.all() 

    contexto = {
        'informacion': informacion,
    }

    return render(request, 'projectos/proyectos.html', contexto)

home/templates/home/base.html
{% load static %} <!-- Carga de archivos estáticos usando el motor de plantillas de Django -->


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Enlace a Google Fonts para tipos de fuentes -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Playpen+Sans:wght@200;300&display=swap"
        rel="stylesheet">


    <!-- Cargar estilos CSS personalizados desde archivos estáticos -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <title>Ricardo Gomez</title>
</head>

<body>
    <div class="row fondo align-items-center">
        <h1 class="text-dark text-center">BACKEND DEVELOPER</h1>
    </div>

    <!-- comienzo de mi barra de navegacion -->
    <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top rounded-3 m-2 ">

        <div class="container-fluid">

            <a class="navbar-brand" href="#"><img src="{% static 'img/logo.svg' %}" width="30px"></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    

                    <!-- copiado -->
                    <li class="nav-item  active  px-lg-4">

                        <a class="nav-link text-uppercase text-expanded" href="{% url 'Home:home' %}">Home</a>
                    </li>

                    <li class="nav-item  px-lg-4">
                        <a class="nav-link text-uppercase text-expanded" href="{% url 'Projects:proyectos' %}">Projects</a>
                    </li>
                   
                    
                    
                    <!-- fin copiado -->

                    
                </ul>

            </div>
        </div>
    </nav>
    <!-- termina mi barra de navegacion -->


    <!-- Contenido que puede cambiar según la página -->
    {% block content %}
    {% endblock %}



    <!-- Comienza footer -->
    <div class="container p-4 mt-5 bg-light text-center">
        Copyright 2023 created by Ricardo Gomez
    </div>




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


</body>

</html>

home/templates/home/index.html
{% extends "home/base.html" %}

{% load static %}


{% block content %}


<!-- Contenido -->
<div class="container mt-4 px-3 ">
    <div class="row">

        <!-- contendor de la foto -->
        <div class="col-sm-12 col-md-4">
            <div style="text-align: center;">
                <img src="{% static 'img/Doraemon.jpg' %}" class="img-fluid" alt="">


            </div>
            <div class="row text-center py-2">
                <h1 class="tipoLetra">Hi, i am Ricardo</h1>
            </div>
        </div>




        <!-- contendor de la informacion personal -->
        <div class="col-sm-12 col-md-8 ">
            <h4 style="text-align: center" class="text-dark tipoLetra">skills</h4>
            <div class="container m-3 text-center d-flex flex-wrap justify-content-center">
                <span style="background-color: rgb(167, 229, 244);"
                    class="border border-2 rounded-pill m-2 p-2 tipoLetra2">
                    PostgreSQL
                </span>
                <span style="background-color: rgb(225, 241, 182);"
                    class="border border-2 rounded-pill m-2 p-2 tipoLetra2 ">
                    mySQL
                </span>
                <span style="background-color: rgb(184, 243, 175);"
                    class="border border-2 rounded-pill m-2 p-2 tipoLetra2">
                    Python
                </span>
                <span style="background-color: rgb(239, 179, 236);"
                    class="border border-2 rounded-pill m-2 p-2 tipoLetra2">
                    Django,
                </span>
                <span style="background-color: rgb(252, 219, 170);"
                    class="border border-2 rounded-pill m-2 p-2 tipoLetra2">
                    docker
                </span>
                <span style="background-color: rgb(202, 244, 167);"
                    class="border border-2 rounded-pill m-2 p-2 tipoLetra2">
                    Bootstrap,
                </span>
            </div>

            <!-- idiomas  -->
            <h4 style="text-align: center" class="text-dark tipoLetra mt-5">Languages:</h4>
            <div class="container  text-center d-flex flex-wrap justify-content-center tipoLetra2 mt-2">
                <span>English: High Proficiency</span>
            </div>
            <div class="container  text-center d-flex flex-wrap justify-content-center tipoLetra2 mt-2">
                <span>Japanese: Intermediate-High Proficiency </span>
            </div>
            <div class="container  text-center d-flex flex-wrap justify-content-center tipoLetra2 mt-2">
                <span>spanish: Native </span>
            </div>
            <!-- hubicacion -->

            <h4 style="text-align: center" class="text-dark tipoLetra mt-5">Current location:</h4>
            <div class="container  text-center d-flex flex-wrap justify-content-center tipoLetra2">
                <span>Japan, hokkaido, sapporo</span>
            </div>

            <!-- correo -->
            <h4 style="text-align: center" class="text-dark tipoLetra mt-5">Email:</h4>
            <div class="container  text-center tipoLetra2">
                <span class="d-block mb-2">ricardoantoniogomezvillalobos@gmail.com</span>

                <span class="d-block mb-2">ricardoantoniogomezvillalobos@outlook.jp</span>
            </div>

            <!-- Social networks -->

            <h4 style="text-align: center" class="text-dark tipoLetra mt-5">social networks</h4>
            <div class="container  text-center d-flex flex-wrap justify-content-center tipoLetra2">



                <div class="social-icons">
                    <a href="https://www.facebook.com/antonio.villalobos.3705/" target="_blank" class="icon">
                        <img src="{% static 'img/facebook.png' %}" width="30px" class="mx-3">
                    </a>

                    <a href="https://www.instagram.com/ricardogomez902/?hl=en" target="_blank" class="icon">
                        <img src="{% static 'img/instagram.svg' %}" width="30px" class="mx-3">
                    </a>




                    <a href="https://www.linkedin.com/in/ricardo-antonio-gomez-villalobos-659369296/" target="_blank" class="icon">
                        <img src="{% static 'img/linkedin.svg' %}" width="30px" class="mx-3">
                    </a>

                    <a href="https://github.com/bardack134" target="_blank" class="icon">
                        <img src="{% static 'img/github.svg' %}" width="30px" class="mx-3">
                    </a>
                </div>
            </div>
        </div>




    </div>
</div>
</div>





{% endblock %}

projectos/templates/projectos/proyectos.html
{% extends "home/base.html" %}

{% load static %}


{% block content %}



<!-- PROYECTOS -->

<div class="container mt-5 text-center d-flex flex-wrap justify-content-center">
    {% for i in informacion %}
    <!-- proyecto1 -->
    <div class="card  mx-1 mb-3   " style="width: 21rem;">
        <img src="{{ i.imagen.url }}" class="card-img-top" style="height: 200px;">
        <div class="card-body">
            <h5 class="card-title">{{ i.titulo }}</h5>
            <p class="card-text" style="text-align: justify;">{{ i.introduccion }}</p>
            <a data-bs-toggle="modal" data-bs-target="#detallesModal{{ i.id }}" class="btn btn-info">View details</a>
        </div>
    </div>

    <!-- Ventana modal correspondiente a la tarjeta actual -->

    <div class="modal fade " id="detallesModal{{ i.id }}" tabindex="-1" aria-labelledby="detallesModalLabel{{ i.id }}" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="detallesModalLabel{{ i.id }}">{{ i.titulo }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    <img src="{{ i.imagen.url }}" class="img-fluid" style="height: 200px;">
                    <!-- introduccion -->
                    <p style="text-align: justify; font-weight: bold;" class="text-uppercase "> INTRODUCTION </p>
                    <p style="text-align: justify;">{{ i.introduccion }}</p>
                    <!-- link github -->
                    <p style="text-align: justify; font-weight: bold;" class="text-uppercase "> LINK GITHUB</p>
                    <a href="{{ i.github_link }}" target="_blank" style="text-align: justify;">{{ i.github_link }}</a>
                    
                    <!-- link del proyecto -->
                    

                    <p style="text-align: justify; font-weight: bold;" class="text-uppercase mt-3"> VIEW PROJECT </p>
                    <a href="{{ i.link_proyecto }}" target="_blank" style="text-align: justify;">{{ i.link_proyecto }}</a>
                    
                  
                    <!-- tecnologias usadas -->
                    <p style="text-align: justify; font-weight: bold;" class="text-uppercase mt-3"> TECHNOLOGIES AND TOOLS
                    </p>
                    <p style="text-align: justify;">{{ i.herramientas }}</p>

                    <!-- resultados y aprendizaje -->
                    <p style="text-align: justify; font-weight: bold;" class="text-uppercase mt-3"> RESULTS AND LEARNINGS
                    </p>
                    <p style="text-align: justify;">{{ i.resultadosLogros }}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

                </div>
            </div>
        </div>
    </div>

    {% endfor %}
</div>






{% endblock %}